name: Promote Dev → Stage

on:
  workflow_dispatch:

jobs:
  sync-dev-stage:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure Dev AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Sync S3 dev→stage
      run: aws s3 sync s3://my-svg-upload-bucket/dev/icon/ s3://stage-svg-bucket/stage/icon/ --delete
