name: Upload SVG to S3

on:
  push:
    paths:
      - "icon/**.svg" # Only trigger when SVG files in icon/ are changed

permissions:
  contents: read
  id-token: write

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        profile: [dev, qa] # Upload to both dev and qa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Upload SVG files to ${{ matrix.profile }}
        run: |
          aws s3 sync ./icon/ s3://my-svg-upload-bucket/${{ matrix.profile }}/icon/ \
            --delete \
            --exclude "*" \
            --include "*.svg"
